name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # openssl_location: /usr/lib/ssl
  openssl_location: /usr/local/ssl
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:        
      - name: List OpenSSL directories
        run: |
          sudo find libssl.a / | grep libssl.a
          sudo find libcrypto.a / | grep libcrypto.a
          ls ${{ env.openssl_location }}
          ls ${{ env.openssl_location }}/bin
          ls ${{ env.openssl_location }}/include
          ls ${{ env.openssl_location }}/lib
