name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # openssl_location: /usr/lib/ssl
  openssl_location: /usr/lib/x86_64-linux-gnu
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:        
      - name: List OpenSSL directories
        run: |
          ls ${{ env.openssl_location }}
          ls ${{ env.openssl_location }}/bin
          ls ${{ env.openssl_location }}/include
          ls ${{ env.openssl_location }}/lib
