name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:        
      - name: List OpenSSL directories
        run: |
          openssl version -d
          echo "LibSSL path:"
          echo $LIBSSL_PATH
          echo "LibCrypto path:"
          echo $LIBCRYPTO_PATH
