name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:        
      - name: List OpenSSL directories
        run: |
          openssl version -d
          ls /usr/lib/ssl
          ls /usr/lib/ssl/bin
          ls /usr/lib/ssl/include
          ls /usr/lib/ssl/lib
